@echo off
REM backup-automatico.bat - Backup Automático Git Silencioso (Windows)
REM Sistema: Assistente Pessoal IA

setlocal enabledelayedexpansion

set TIPO=%1
if "%TIPO%"=="" set TIPO=manual

REM Verificar se Git está inicializado
if not exist ".git" (
    echo ⚠️  Git não inicializado. Execute: git init
    exit /b 1
)

REM Verificar se há mudanças
git diff --quiet >nul 2>&1
if %ERRORLEVEL%==0 (
    git diff --cached --quiet >nul 2>&1
    if !ERRORLEVEL!==0 (
        REM Nenhuma mudança
        exit /b 0
    )
)

REM Contar arquivos modificados
for /f %%i in ('git status --porcelain ^| find /c /v ""') do set ARQUIVOS_MOD=%%i

REM Ler estatísticas do cache
set CONVERSAS=0
set STREAK=0
if exist ".assistant-core\data\dashboard-cache.yaml" (
    for /f "tokens=2" %%i in ('findstr "conversas_total:" ".assistant-core\data\dashboard-cache.yaml" 2^>nul') do set CONVERSAS=%%i
    for /f "tokens=2" %%i in ('findstr "^streak_dias:" ".assistant-core\data\dashboard-cache.yaml" 2^>nul') do set STREAK=%%i
)

REM Criar mensagem de commit
set TIMESTAMP=%date% %time:~0,5%

REM Add e commit
git add -A >nul 2>&1
git commit -m "✅ Backup automático: %TIPO% - Data: %TIMESTAMP% - Arquivos: %ARQUIVOS_MOD% - Status: %CONVERSAS% conversas, Streak: %STREAK% dias - 🤖 Generated by Assistente Pessoal IA" --quiet >nul 2>&1

REM Push assíncrono se remoto configurado
git remote | findstr "origin" >nul 2>&1
if %ERRORLEVEL%==0 (
    start /b git push origin main --quiet >nul 2>&1
)

REM Feedback visual
echo 💾 Backup automático feito às %time:~0,5% ✓

endlocal
